@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Creating commit...
git commit -m "Add Courier step-by-step actions: Pick Up, Arrive at Customer, and Mark Delivered"
echo Setting main branch...
git branch -M main
echo Setting remote URL...
git remote remove origin 2>nul
git remote add origin https://github.com/zeriouil/DelivriLi.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
