@echo off
echo Adding files...
git add .
echo Creating commit...
git commit -m "Fix courier Pick Up, Arrive, Delivered step buttons and status tracking"
echo Pushing to GitHub...
git push origin main
echo Done!
pause
