@echo off
echo Adding files...
git add .
echo Creating commit...
git commit -m "Show full map with slim waiting spinner when no active jobs, hide empty jobs panel"
echo Pushing to GitHub...
git push origin main
echo Done!
pause
